parameters:
  name: ''
  displayName: ''
  targetOS: ''
  pool: {}
  isOfficialBuild: false

jobs:
  - template: eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      enableTelemetry: true
      graphFileGeneration:
        enabled: true
        includeToolset: true
      helixRepo: dotnet/corefxlab
      jobs:
      - job: ${{ parameters.name }}
        timeoutInMinutes: 90
        displayName: ${{ parameters.displayName }}
        variables:
          - ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
            - name: _buildScript
              value: build.cmd
          - ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
            - name: _buildScript
              value: ./build.sh
          
          - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            - name: _buildArguments
              value: -Configuration $(_BuildConfig) /p:VersionSuffix=$(Build.BuildNumber) -ci -sign /p:BuildPackages=true -pack
            - name: _SignType
              value: real
            - name: _TeamName
              value: DotNetCore
            - group: DotNet-MyGet-Publish
            - group: DotNet-Symbol-Server-Pats
            - name: _SymwebSymbolServerPath
              value: https://microsoft.artifacts.visualstudio.com/DefaultCollection
            - name: _MsdlSymbolServerPath
              value: https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection

          - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            - name: _buildArguments
              value: $(_BuildConfig) /p:UpdateXlfOnBuild=true

        pool: ${{ parameters.pool }}

        strategy:
          matrix:
            ${{ if eq(parameters.isOfficialBuild, 'false') }}:
              x64_Debug:
                _BuildConfig: Debug

            x64_Release:
              _BuildConfig: Release

        steps:
          - script: $(_buildScript) $(_buildArguments)
            displayName: Build and Test
        