// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// NOTE: This file is generated via a T4 template. Please do not edit this file directly. Any changes should be made
// in Signed.tt.

using System.Runtime.CompilerServices;

namespace System.Text
{
    public static partial class PrimitiveParser
    {
        #region Helpers

        private const sbyte maxValueSbyteDiv10 = sbyte.MaxValue / 10;
        private const short maxValueShortDiv10 = short.MaxValue / 10;
        private const int maxValueIntDiv10 = int.MaxValue / 10;
        private const long maxValueLongDiv10 = long.MaxValue / 10;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool IsDigit(int i)
        {
            return (uint)(i - '0') <= ('9' - '0');
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool IsValid(uint i)
        {
            return i <= (uint)TextEncoder.Symbol.D9;
        }

        // If parsedValue > (sbyte.MaxValue / 10), any more appended digits will cause overflow.
        // if parsedValue == (sbyte.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WillOverFlow(sbyte value, int nextDigit, int sign)
        {
            bool nextDigitTooLarge = nextDigit > 8 || (sign > 0 && nextDigit > 7);
            return (value > maxValueSbyteDiv10 || (value == maxValueSbyteDiv10 && nextDigitTooLarge));
        }

        // If parsedValue > (short.MaxValue / 10), any more appended digits will cause overflow.
        // if parsedValue == (short.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WillOverFlow(short value, int nextDigit, int sign)
        {
            bool nextDigitTooLarge = nextDigit > 8 || (sign > 0 && nextDigit > 7);
            return (value > maxValueShortDiv10 || (value == maxValueShortDiv10 && nextDigitTooLarge));
        }

        // If parsedValue > (int.MaxValue / 10), any more appended digits will cause overflow.
        // if parsedValue == (int.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WillOverFlow(int value, int nextDigit, int sign)
        {
            bool nextDigitTooLarge = nextDigit > 8 || (sign > 0 && nextDigit > 7);
            return (value > maxValueIntDiv10 || (value == maxValueIntDiv10 && nextDigitTooLarge));
        }

        // If parsedValue > (long.MaxValue / 10), any more appended digits will cause overflow.
        // if parsedValue == (long.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static bool WillOverFlow(long value, int nextDigit, int sign)
        {
            bool nextDigitTooLarge = nextDigit > 8 || (sign > 0 && nextDigit > 7);
            return (value > maxValueLongDiv10 || (value == maxValueLongDiv10 && nextDigitTooLarge));
        }

        #endregion

        public static bool TryParseSByte(ReadOnlySpan<byte> text, out sbyte value, out int bytesConsumed, TextFormat format = default, TextEncoder encoder = null)
        {
            encoder = encoder ?? TextEncoder.Utf8;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseSByte(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseSByte(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.NonPortableCast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseSByte(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseSByte(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            int sign = 1;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                sign = -1;
            }

            int signConsumed = 0;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.PlusSign || (TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                signConsumed = thisSymbolConsumed;
                if (!encoder.TryParseSymbol(text.Slice(signConsumed), out nextSymbol, out thisSymbolConsumed))
                {
                    value = default;
                    bytesConsumed = 0;
                    return false;
                }
            }

            if (nextSymbol > 9)
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            int parsedValue = (int)nextSymbol;
            int index = signConsumed + thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (sbyte)(parsedValue * sign);
                    return true;
                }

                // If parsedValue > (sbyte.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (sbyte.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
                bool positive = sign > 0;
                bool nextDigitTooLarge = nextSymbol > 8 || (positive && nextSymbol > 7);
                if (parsedValue > sbyte.MaxValue / 10 || (parsedValue == sbyte.MaxValue / 10 && nextDigitTooLarge))
                {
                    bytesConsumed = 0;
                    value = default;
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + (int)nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (sbyte)(parsedValue * sign);
            return true;
        }

        public static bool TryParseInt16(ReadOnlySpan<byte> text, out short value, out int bytesConsumed, TextFormat format = default, TextEncoder encoder = null)
        {
            encoder = encoder ?? TextEncoder.Utf8;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseInt16(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseInt16(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.NonPortableCast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseInt16(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseInt16(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            int sign = 1;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                sign = -1;
            }

            int signConsumed = 0;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.PlusSign || (TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                signConsumed = thisSymbolConsumed;
                if (!encoder.TryParseSymbol(text.Slice(signConsumed), out nextSymbol, out thisSymbolConsumed))
                {
                    value = default;
                    bytesConsumed = 0;
                    return false;
                }
            }

            if (nextSymbol > 9)
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            int parsedValue = (int)nextSymbol;
            int index = signConsumed + thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (short)(parsedValue * sign);
                    return true;
                }

                // If parsedValue > (short.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (short.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
                bool positive = sign > 0;
                bool nextDigitTooLarge = nextSymbol > 8 || (positive && nextSymbol > 7);
                if (parsedValue > short.MaxValue / 10 || (parsedValue == short.MaxValue / 10 && nextDigitTooLarge))
                {
                    bytesConsumed = 0;
                    value = default;
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + (int)nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (short)(parsedValue * sign);
            return true;
        }

        public static bool TryParseInt32(ReadOnlySpan<byte> text, out int value, out int bytesConsumed, TextFormat format = default, TextEncoder encoder = null)
        {
            bool isDefault = format.IsDefault;

            if (!isDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            bool isHex = format.IsHexadecimal;

            encoder = encoder ?? TextEncoder.Utf8;

            if (encoder.IsInvariantUtf8)
            {
                return isHex ? InvariantUtf8.Hex.TryParseInt32(text, out value, out bytesConsumed) :
                        InvariantUtf8.TryParseInt32(text, out value, out bytesConsumed);
            }
            else if (encoder.IsInvariantUtf16)
            {
                /*return isHex ? InvariantUtf16.Hex.TryParseInt32(text, out value, out bytesConsumed) :
                    InvariantUtf16.TryParseInt32(text, out value, out bytesConsumed);*/
                ReadOnlySpan<char> utf16Text = text.NonPortableCast<byte, char>();
                bool result = isHex ? InvariantUtf16.Hex.TryParseInt32(utf16Text, out value, out int charsConsumed) :
                    InvariantUtf16.TryParseInt32(utf16Text, out value, out charsConsumed);
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (isHex)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(isDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            int textLength = text.Length;
            if (textLength < 1) goto FalseExit;

            ref byte textByte = ref text.DangerousGetPinnableReference();
            if (!encoder.TryParseSymbol(ref textByte, out uint symbol, out int consumed)) goto FalseExit;

            sbyte sign = 1;
            int index = 0;
            if (symbol == (uint)TextEncoder.Symbol.MinusSign)
            {
                sign = -1;
                index += consumed;
                if (index >= textLength) goto FalseExit;
                if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto FalseExit;
            }
            else if (symbol == (uint)TextEncoder.Symbol.PlusSign)
            {
                index += consumed;
                if (index >= textLength) goto FalseExit;
                if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto FalseExit;
            }

            int answer = 0;
            if (IsValid(symbol))
            {
                int numBytes = consumed;
                if (symbol == (uint)TextEncoder.Symbol.D0)
                {
                    do
                    {
                        index += consumed;
                        if (index >= textLength) goto Done;
                        if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto Done;
                    } while (symbol == (uint)TextEncoder.Symbol.D0);
                    if (!IsValid(symbol)) goto Done;
                }

                int firstNonZeroDigitIndex = index;
                if (textLength - firstNonZeroDigitIndex < Int32OverflowLength * numBytes)
                {
                    do
                    {
                        answer = answer * 10 + (int)symbol - (int)TextEncoder.Symbol.D0;
                        index += consumed;
                        if (index >= textLength) goto Done;
                        if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto Done;
                    } while (IsValid(symbol));
                }
                else
                {
                    do
                    {
                        answer = answer * 10 + (int)symbol - (int)TextEncoder.Symbol.D0;
                        index += consumed;
                        if (index - firstNonZeroDigitIndex == Int32OverflowLength * numBytes - 1)
                        {
                            if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto Done;
                            if (IsValid(symbol))
                            {
                                symbol -= (int)TextEncoder.Symbol.D0;
                                if (WillOverFlow(answer, (int)symbol, sign)) goto FalseExit;
                                answer = answer * 10 + (int)symbol;
                                index += consumed;
                            }
                            goto Done;
                        }
                        if (!encoder.TryParseSymbol(ref Unsafe.Add(ref textByte, index), out symbol, out consumed)) goto Done;
                    } while (IsValid(symbol));
                }
                goto Done;
            }

            FalseExit:
            bytesConsumed = 0;
            value = 0;
            return false;

            Done:
            bytesConsumed = index;
            value = answer * sign;
            return true;
        }

        public static bool TryParseInt64(ReadOnlySpan<byte> text, out long value, out int bytesConsumed, TextFormat format = default, TextEncoder encoder = null)
        {
            encoder = encoder ?? TextEncoder.Utf8;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseInt64(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseInt64(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.NonPortableCast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseInt64(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseInt64(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            int sign = 1;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                sign = -1;
            }

            int signConsumed = 0;
            if ((TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.PlusSign || (TextEncoder.Symbol)nextSymbol == TextEncoder.Symbol.MinusSign)
            {
                signConsumed = thisSymbolConsumed;
                if (!encoder.TryParseSymbol(text.Slice(signConsumed), out nextSymbol, out thisSymbolConsumed))
                {
                    value = default;
                    bytesConsumed = 0;
                    return false;
                }
            }

            if (nextSymbol > 9)
            {
                value = default;
                bytesConsumed = 0;
                return false;
            }

            long parsedValue = (long)nextSymbol;
            int index = signConsumed + thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (long)(parsedValue * sign);
                    return true;
                }

                // If parsedValue > (long.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (long.MaxValue / 10), any nextDigit greater than 7 or 8 (depending on sign) implies overflow.
                bool positive = sign > 0;
                bool nextDigitTooLarge = nextSymbol > 8 || (positive && nextSymbol > 7);
                if (parsedValue > long.MaxValue / 10 || (parsedValue == long.MaxValue / 10 && nextDigitTooLarge))
                {
                    bytesConsumed = 0;
                    value = default;
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + (long)nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (long)(parsedValue * sign);
            return true;
        }
    }
}
