// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// NOTE: This file is generated via a T4 template. Please do not edit this file directly. Any changes should be made
// in Unsigned.tt.

namespace System.Text
{
    public static partial class PrimitiveParser
    {

        public static bool TryParseByte(ReadOnlySpan<byte> text, out byte value, out int bytesConsumed, TextFormat format = default(TextFormat), TextEncoder encoder = null)
        {
            encoder = encoder == null ? TextEncoder.Utf8 : encoder;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseByte(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseByte(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.Cast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseByte(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseByte(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default(byte);
                bytesConsumed = 0;
                return false;
            }

            if (nextSymbol > 9)
            {
                value = default(byte);
                bytesConsumed = 0;
                return false;
            }

            uint parsedValue = nextSymbol;
            int index = thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (byte) parsedValue;
                    return true;
                }

                // If parsedValue > (byte.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (byte.MaxValue / 10), any nextDigit greater than 5 implies overflow.
                if (parsedValue > byte.MaxValue / 10 || (parsedValue == byte.MaxValue / 10 && nextSymbol > 5))
                {
                    bytesConsumed = 0;
                    value = default(byte);
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (byte) parsedValue;
            return true;
        }

        public static bool TryParseUInt16(ReadOnlySpan<byte> text, out ushort value, out int bytesConsumed, TextFormat format = default(TextFormat), TextEncoder encoder = null)
        {
            encoder = encoder == null ? TextEncoder.Utf8 : encoder;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseUInt16(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseUInt16(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.Cast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseUInt16(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseUInt16(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default(ushort);
                bytesConsumed = 0;
                return false;
            }

            if (nextSymbol > 9)
            {
                value = default(ushort);
                bytesConsumed = 0;
                return false;
            }

            uint parsedValue = nextSymbol;
            int index = thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (ushort) parsedValue;
                    return true;
                }

                // If parsedValue > (ushort.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (ushort.MaxValue / 10), any nextDigit greater than 5 implies overflow.
                if (parsedValue > ushort.MaxValue / 10 || (parsedValue == ushort.MaxValue / 10 && nextSymbol > 5))
                {
                    bytesConsumed = 0;
                    value = default(ushort);
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (ushort) parsedValue;
            return true;
        }

        public static bool TryParseUInt32(ReadOnlySpan<byte> text, out uint value, out int bytesConsumed, TextFormat format = default(TextFormat), TextEncoder encoder = null)
        {
            encoder = encoder == null ? TextEncoder.Utf8 : encoder;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseUInt32(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseUInt32(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.Cast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseUInt32(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseUInt32(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default(uint);
                bytesConsumed = 0;
                return false;
            }

            if (nextSymbol > 9)
            {
                value = default(uint);
                bytesConsumed = 0;
                return false;
            }

            uint parsedValue = nextSymbol;
            int index = thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (uint) parsedValue;
                    return true;
                }

                // If parsedValue > (uint.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (uint.MaxValue / 10), any nextDigit greater than 5 implies overflow.
                if (parsedValue > uint.MaxValue / 10 || (parsedValue == uint.MaxValue / 10 && nextSymbol > 5))
                {
                    bytesConsumed = 0;
                    value = default(uint);
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (uint) parsedValue;
            return true;
        }

        public static bool TryParseUInt64(ReadOnlySpan<byte> text, out ulong value, out int bytesConsumed, TextFormat format = default(TextFormat), TextEncoder encoder = null)
        {
            encoder = encoder == null ? TextEncoder.Utf8 : encoder;

            if (!format.IsDefault && format.HasPrecision)
            {
                throw new NotImplementedException("Format with precision not supported.");
            }

            if (encoder.IsInvariantUtf8)
            {
                if (format.IsHexadecimal)
                {
                    return InvariantUtf8.Hex.TryParseUInt64(text, out value, out bytesConsumed);
                }
                else
                {
                    return InvariantUtf8.TryParseUInt64(text, out value, out bytesConsumed);
                }
            }
            else if (encoder.IsInvariantUtf16)
            {
                ReadOnlySpan<char> utf16Text = text.Cast<byte, char>();
                int charsConsumed;
                bool result;
                if (format.IsHexadecimal)
                {
                    result = InvariantUtf16.Hex.TryParseUInt64(utf16Text, out value, out charsConsumed);
                }
                else
                {
                    result = InvariantUtf16.TryParseUInt64(utf16Text, out value, out charsConsumed);
                }
                bytesConsumed = charsConsumed * sizeof(char);
                return result;
            }

            if (format.IsHexadecimal)
            {
                throw new NotImplementedException("The only supported encodings for hexadecimal parsing are InvariantUtf8 and InvariantUtf16.");
            }

            if (!(format.IsDefault || format.Symbol == 'G' || format.Symbol == 'g'))
            {
                throw new NotImplementedException(String.Format("Format '{0}' not supported.", format.Symbol));
            }

            uint nextSymbol;
            int thisSymbolConsumed;
            if (!encoder.TryParseSymbol(text, out nextSymbol, out thisSymbolConsumed))
            {
                value = default(ulong);
                bytesConsumed = 0;
                return false;
            }

            if (nextSymbol > 9)
            {
                value = default(ulong);
                bytesConsumed = 0;
                return false;
            }

            ulong parsedValue = nextSymbol;
            int index = thisSymbolConsumed;

            while (index < text.Length)
            {
                bool success = encoder.TryParseSymbol(text.Slice(index), out nextSymbol, out thisSymbolConsumed);
                if (!success || nextSymbol > 9)
                {
                    bytesConsumed = index;
                    value = (ulong) parsedValue;
                    return true;
                }

                // If parsedValue > (ulong.MaxValue / 10), any more appended digits will cause overflow.
                // if parsedValue == (ulong.MaxValue / 10), any nextDigit greater than 5 implies overflow.
                if (parsedValue > ulong.MaxValue / 10 || (parsedValue == ulong.MaxValue / 10 && nextSymbol > 5))
                {
                    bytesConsumed = 0;
                    value = default(ulong);
                    return false;
                }

                index += thisSymbolConsumed;
                parsedValue = parsedValue * 10 + nextSymbol;
            }

            bytesConsumed = text.Length;
            value = (ulong) parsedValue;
            return true;
        }
    }
}
