parameters:
  name: ''
  displayName: ''
  targetOS: ''
  pool: {}
  isOfficialBuild: false

jobs:
  - template: ../eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      enableTelemetry: true
      graphFileGeneration:
        enabled: true
        includeToolset: true
      helixRepo: dotnet/corefxlab
      jobs:
      - job: ${{ parameters.name }}
        timeoutInMinutes: 90
        displayName: ${{ parameters.displayName }}
        variables:
          - ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
            - name: _buildScript
              value: build.cmd
          - ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
            - name: _buildScript
              value: ./build.sh
          
          - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            - name: _buildArguments
              value: -Configuration $(_BuildConfig) -BuildVersion $(Build.BuildNumber)
            - name: _SignType
              value: real
            - name: _TeamName
              value: DotNetCore
            - group: DotNet-MyGet-Publish
            - group: DotNet-Symbol-Server-Pats
            - name: _SymwebSymbolServerPath
              value: https://microsoft.artifacts.visualstudio.com/DefaultCollection
            - name: _MsdlSymbolServerPath
              value: https://microsoftpublicsymbols.artifacts.visualstudio.com/DefaultCollection

          - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            - name: _buildArguments
              value: $(_BuildConfig)

        pool: ${{ parameters.pool }}

        strategy:
          matrix:
            ${{ if eq(parameters.isOfficialBuild, 'false') }}:
              x64_Debug:
                _BuildConfig: Debug

            x64_Release:
              _BuildConfig: Release

        steps:
          - script: $(_buildScript) $(_buildArguments)
            displayName: Build and Test
          
          - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            - script: package.cmd -Configuration $(_BuildConfig) -ApiKey $(dotnet-myget-org-api-key) -BuildVersion $(Build.BuildNumber) -Sign -SignType $(_SignType) -IsStableRelease $(_IsStableRelease)
              displayName: Build and publish Nuget packages

            - script: dotnetcli\dotnet.exe msbuild tools\package-steps.proj /t:PublishSymbolPackages /p:SymbolServerPath=$(_SymwebSymbolServerPath) /p:SymbolServerPAT=$(symweb-symbol-server-pat)
              displayName: Publish symbols to symweb

            - script: dotnetcli\dotnet.exe msbuild tools\package-steps.proj /t:PublishSymbolPackages /p:SymbolServerPath=$(_MsdlSymbolServerPath) /p:SymbolServerPAT=$(microsoft-symbol-server-pat)
              displayName: Publish symbols to msdl

            - task: PublishBuildArtifacts@1
              displayName: Publish packages to artifacts container
              inputs:
                pathToPublish: $(Build.SourcesDirectory)/packages
                artifactName: packages
                artifactType: container

            - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              - template: eng\common\templates\post-build\post-build.yml
                parameters:
                  # Symbol validation isn't being very reliable lately. This should be enabled back
                  # once this issue is resolved: https://github.com/dotnet/arcade/issues/2871
                  enableSymbolValidation: false