// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// THIS FILE IS AUTOGENERATED

using System;
using System.Globalization;
using Xunit;

namespace System.Text.Formatting.Tests
{
    public partial class SystemTextFormattingTests
    {
        public void CheckTimeSpan(TimeSpan value, string format)
        {
            var parsed = Format.Parse(format);
            var formatter = new StringFormatter(pool);
            formatter.Append(value, parsed);
            var result = formatter.ToString();
            var clrResult = value.ToString(format, CultureInfo.InvariantCulture);
            Assert.Equal(clrResult, result);
        }
        
        [Fact]
        public void TimeSpanFormatG()
        {
            
            // format G
            CheckTimeSpan(TimeSpan.MinValue, "G");
            CheckTimeSpan(TimeSpan.MaxValue, "G");
            CheckTimeSpan(new TimeSpan(1944698421), "G");
            CheckTimeSpan(new TimeSpan(82938987), "G");
            CheckTimeSpan(new TimeSpan(1978120584), "G");
            CheckTimeSpan(new TimeSpan(503141639), "G");
            CheckTimeSpan(new TimeSpan(586695490), "G");
            CheckTimeSpan(new TimeSpan(-44121223), "G");
            CheckTimeSpan(new TimeSpan(1873109777), "G");
            CheckTimeSpan(new TimeSpan(384250645), "G");
            CheckTimeSpan(new TimeSpan(-276980243), "G");
            CheckTimeSpan(new TimeSpan(-545130237), "G");
            CheckTimeSpan(new TimeSpan(192234178), "G");
            CheckTimeSpan(new TimeSpan(-642542568), "G");
            CheckTimeSpan(new TimeSpan(-1574304687), "G");
            CheckTimeSpan(new TimeSpan(238867855), "G");
            CheckTimeSpan(new TimeSpan(-9707235), "G");
            CheckTimeSpan(new TimeSpan(-752141784), "G");
            CheckTimeSpan(new TimeSpan(-1628014271), "G");
            CheckTimeSpan(new TimeSpan(983164301), "G");
        }
        
        [Fact]
        public void TimeSpanFormatc()
        {
            
            // format c
            CheckTimeSpan(TimeSpan.MinValue, "c");
            CheckTimeSpan(TimeSpan.MaxValue, "c");
            CheckTimeSpan(new TimeSpan(2030513564), "c");
            CheckTimeSpan(new TimeSpan(-1880026379), "c");
            CheckTimeSpan(new TimeSpan(-763245925), "c");
            CheckTimeSpan(new TimeSpan(559460645), "c");
            CheckTimeSpan(new TimeSpan(314172980), "c");
            CheckTimeSpan(new TimeSpan(-1944932857), "c");
            CheckTimeSpan(new TimeSpan(1057841790), "c");
            CheckTimeSpan(new TimeSpan(-59716933), "c");
            CheckTimeSpan(new TimeSpan(-771325288), "c");
            CheckTimeSpan(new TimeSpan(1692478753), "c");
            CheckTimeSpan(new TimeSpan(1285702982), "c");
            CheckTimeSpan(new TimeSpan(263643141), "c");
            CheckTimeSpan(new TimeSpan(-199121113), "c");
            CheckTimeSpan(new TimeSpan(-1769501624), "c");
            CheckTimeSpan(new TimeSpan(-812621779), "c");
            CheckTimeSpan(new TimeSpan(-625188670), "c");
            CheckTimeSpan(new TimeSpan(-1829558478), "c");
            CheckTimeSpan(new TimeSpan(1744216764), "c");
        }
        
    }
}
