//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.DataFrame.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resize down.
        /// </summary>
        public static string CannotResizeDown {
            get {
                return ResourceManager.GetString("CannotResizeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index cannot be greater than the Column&apos;s Length.
        /// </summary>
        public static string ColumnIndexOutOfRange {
            get {
                return ResourceManager.GetString("ColumnIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column is immutable.
        /// </summary>
        public static string ImmutableStringColumn {
            get {
                return ResourceManager.GetString("ImmutableStringColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column does not exist.
        /// </summary>
        public static string InvalidColumnName {
            get {
                return ResourceManager.GetString("InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapIndices exceeds column length.
        /// </summary>
        public static string MapIndicesExceedsColumnLenth {
            get {
                return ResourceManager.GetString("MapIndicesExceedsColumnLenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column lengths are mismatched.
        /// </summary>
        public static string MismatchedColumnLengths {
            get {
                return ResourceManager.GetString("MismatchedColumnLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rowCount differs from Column length for Column .
        /// </summary>
        public static string MismatchedRowCount {
            get {
                return ResourceManager.GetString("MismatchedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value to be of type.
        /// </summary>
        public static string MismatchedValueType {
            get {
                return ResourceManager.GetString("MismatchedValueType", resourceCulture);
            }
        }
    }
}
