//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Text.Formatting {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision value exceeds maximum allowed.
        /// </summary>
        internal static string PrecisionValueOutOfRange {
            get {
                return ResourceManager.GetString("PrecisionValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse precision specification.
        /// </summary>
        internal static string UnableToParsePrecision {
            get {
                return ResourceManager.GetString("UnableToParsePrecision", resourceCulture);
            }
        }

        internal static string CreateInvalidParameters {
            get {
                return ResourceManager.GetString("CreateInvalidParameters", resourceCulture);
            }
        }

        internal static string FileTypeNotSupported {
            get {
                return ResourceManager.GetString("FileTypeNotSupported", resourceCulture);
            }
        }
        internal static string InvalidTransparencyPercent {
            get {
                return ResourceManager.GetString("InvalidTransparencyPercent", resourceCulture);
            }
        }
        internal static string MalformedFilePath {
            get {
                return ResourceManager.GetString("MalformedFilePath", resourceCulture);
            }
        }
        internal static string NullStreamReferenced {
            get {
                return ResourceManager.GetString("NullStreamReferenced", resourceCulture);
            }
        }
        internal static string ResizeInvalidParameters {
            get {
                return ResourceManager.GetString("ResizeInvalidParameters", resourceCulture);
            }
        }
        internal static string WriteToFileFailed {
            get {
                return ResourceManager.GetString("WriteToFileFailed", resourceCulture);
            }
        }
    }
}
